import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Poppins } from 'next/font/google'

import NavBar from './components/nav/NavBar'
import Footer from './components/footer/Footer'
import CartProvider from './providers/cardProvider'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({ subsets: ['latin'] , weight: ['400', '700']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} text-slate-700`}>

        <Toaster
          toastOptions={{
            style:{
              background: "gb(51 65 85)",
              color: "#fff",
            }
          }}
        />
        <CartProvider>

          <div className='flex flex-col min-h-screen'>
            <NavBar></NavBar>
            <main className='flex-grow'>{children}</main>
            <Footer></Footer>
          </div>

        </CartProvider>
        


      </body>
    </html>
  )
}
